image:
  name: node:12

pipelines:
  default:
    - parallel:
      - step:
          name: Lint
          script:
            - cd cw-metric-alarm
            - npm install
            - npm run lint
      - step:
          name: Test
          script:
            - cd cw-metric-alarm
            - npm install
            - npm run test
      - step:
          name: Webpack
          script:
            - cd cw-metric-alarm
            - npm install
            - npx webpack
          artifacts:
            - cw-metric-alarm/dist/**